import { donationModel } from '@/models/donation';
import type { IDonation } from '@/types';
import { withBothLangs, type Content, type Localized, type Persona } from './personas/types';

/**
 * Buy-me-a-coffee options for the demo persona.
 *
 * Unlike projects or products, a support option is not biographical: it is a rail
 * the money travels on. So the set is authored once, in both languages, and every
 * rail the site can render appears exactly once — one platform hand-off abroad,
 * one at home, a prepared gateway link, card-to-card, a crypto wallet and a live
 * gateway checkout.
 *
 * The destinations are obvious placeholders (`your-name`, an all-zero IBAN, a
 * 16-digit fake card), because seeding real coordinates into a demo database
 * would only ever end with a supporter paying the wrong person. Replace them in
 * the dashboard before going live.
 */

type DonationContent = Content<IDonation>;

const OPTIONS: Localized<DonationContent> = {
  en: [
    {
      title: 'One coffee',
      slug: 'one-coffee',
      description: 'Keeps the writing going and the issues answered.',
      amount: 5,
      currency: 'usd',
      customAmount: false,
      suggestedAmounts: [],
      minAmount: 0,
      maxAmount: 0,
      mode: 'referral',
      region: 'global',
      referral: 'buymeacoffee',
      href: 'https://buymeacoffee.com/your-name',
      recurring: false,
      cups: 1,
      active: true,
      featured: true,
      order: 0,
    },
    {
      title: 'Three coffees',
      slug: 'three-coffees',
      description: 'An evening of maintenance on the libraries I keep free.',
      amount: 15,
      currency: 'usd',
      customAmount: false,
      suggestedAmounts: [],
      minAmount: 0,
      maxAmount: 0,
      mode: 'referral',
      region: 'global',
      referral: 'kofi',
      href: 'https://ko-fi.com/your-name',
      recurring: false,
      cups: 3,
      active: true,
      featured: false,
      order: 1,
    },
    {
      title: 'Monthly support',
      slug: 'monthly-support',
      description: 'A standing coffee, cancelled whenever you like.',
      amount: 10,
      currency: 'usd',
      customAmount: false,
      suggestedAmounts: [],
      minAmount: 0,
      maxAmount: 0,
      mode: 'referral',
      region: 'global',
      referral: 'patreon',
      href: 'https://patreon.com/your-name',
      recurring: true,
      cups: 2,
      active: true,
      featured: false,
      order: 2,
    },
    {
      title: 'Hamyato',
      slug: 'hamyato',
      description: 'Support through the Iranian creator platform.',
      amount: 250000,
      currency: 'toman',
      customAmount: false,
      suggestedAmounts: [],
      minAmount: 0,
      maxAmount: 0,
      mode: 'referral',
      region: 'ir',
      referral: 'hamyato',
      href: 'https://hamyato.io/your-name',
      recurring: false,
      cups: 1,
      active: true,
      featured: false,
      order: 3,
    },
    {
      title: 'Card to card',
      slug: 'card-to-card',
      description: 'Transfer from your own bank app; a QR and the reference are shown before you send.',
      amount: 0,
      currency: 'toman',
      customAmount: true,
      suggestedAmounts: [250000, 500000, 1000000],
      minAmount: 50000,
      maxAmount: 50000000,
      mode: 'card',
      region: 'ir',
      card: { number: '1234123412341234', holder: 'Demo Owner', iban: 'IR000000000000000000000000' },
      recurring: false,
      cups: 2,
      active: true,
      featured: true,
      order: 4,
    },
    {
      title: 'Prepared payment link',
      slug: 'payment-link',
      description: 'A checkout page built in the gateway, opened straight from here.',
      amount: 500000,
      currency: 'toman',
      customAmount: false,
      suggestedAmounts: [],
      minAmount: 0,
      maxAmount: 0,
      mode: 'link',
      region: 'ir',
      linkProvider: 'zarinpal',
      href: 'https://zarinpal.com/pg/StartPay/your-payment-link',
      recurring: false,
      cups: 4,
      active: true,
      featured: false,
      order: 5,
    },
    {
      title: 'Crypto (USDT · TRC-20)',
      slug: 'crypto-usdt',
      description: 'Send from your own wallet. Check the network before you confirm.',
      amount: 10,
      currency: 'usd',
      customAmount: true,
      suggestedAmounts: [5, 10, 25],
      minAmount: 1,
      maxAmount: 1000,
      mode: 'crypto',
      region: 'global',
      crypto: { network: 'tron', address: 'TExampleWalletAddressReplaceMe1234' },
      recurring: false,
      cups: 3,
      active: true,
      featured: false,
      order: 6,
    },
    {
      title: 'Pay by card',
      slug: 'pay-by-card',
      description: 'Card checkout on the gateway page, and back here when it is done.',
      amount: 10,
      currency: 'usd',
      customAmount: false,
      suggestedAmounts: [],
      minAmount: 0,
      maxAmount: 0,
      mode: 'gateway',
      region: 'global',
      gateway: 'stripe',
      recurring: false,
      cups: 2,
      active: true,
      featured: true,
      order: 7,
    },
  ],
  fa: [
    {
      title: 'یک کافی',
      slug: 'one-coffee',
      description: 'کمک می‌کند نوشتن ادامه داشته باشد و سؤال‌ها پاسخ بفرمایند.',
      amount: 5,
      currency: 'usd',
      customAmount: false,
      suggestedAmounts: [],
      minAmount: 0,
      maxAmount: 0,
      mode: 'referral',
      region: 'global',
      referral: 'buymeacoffee',
      href: 'https://buymeacoffee.com/your-name',
      recurring: false,
      cups: 1,
      active: true,
      featured: true,
      order: 0,
    },
    {
      title: 'سه کافی',
      slug: 'three-coffees',
      description: 'یک شب وقت برای نگهداری کتابخانه‌هایی که رایگان منتشر کرده‌ام.',
      amount: 15,
      currency: 'usd',
      customAmount: false,
      suggestedAmounts: [],
      minAmount: 0,
      maxAmount: 0,
      mode: 'referral',
      region: 'global',
      referral: 'kofi',
      href: 'https://ko-fi.com/your-name',
      recurring: false,
      cups: 3,
      active: true,
      featured: false,
      order: 1,
    },
    {
      title: 'حمایت ماهانه',
      slug: 'monthly-support',
      description: 'یک کافی همیشگی، هر وقت خواستی قابل لغو.',
      amount: 10,
      currency: 'usd',
      customAmount: false,
      suggestedAmounts: [],
      minAmount: 0,
      maxAmount: 0,
      mode: 'referral',
      region: 'global',
      referral: 'patreon',
      href: 'https://patreon.com/your-name',
      recurring: true,
      cups: 2,
      active: true,
      featured: false,
      order: 2,
    },
    {
      title: 'حمیاتو',
      slug: 'hamyato',
      description: 'حمایت از طریق پلتفرم ایرانی پشتیبانی از تولیدکننده.',
      amount: 250000,
      currency: 'toman',
      customAmount: false,
      suggestedAmounts: [],
      minAmount: 0,
      maxAmount: 0,
      mode: 'referral',
      region: 'ir',
      referral: 'hamyato',
      href: 'https://hamyato.io/your-name',
      recurring: false,
      cups: 1,
      active: true,
      featured: false,
      order: 3,
    },
    {
      title: 'کارت به کارت',
      slug: 'card-to-card',
      description: 'با اپلیکیشن بانکی خودت انتقال بده؛ قبل از ارسال، کد QR و شناسه را می‌بینی.',
      amount: 0,
      currency: 'toman',
      customAmount: true,
      suggestedAmounts: [250000, 500000, 1000000],
      minAmount: 50000,
      maxAmount: 50000000,
      mode: 'card',
      region: 'ir',
      card: { number: '1234123412341234', holder: 'صاحب حساب نمونه', iban: 'IR000000000000000000000000' },
      recurring: false,
      cups: 2,
      active: true,
      featured: true,
      order: 4,
    },
    {
      title: 'لینک پرداخت آماده',
      slug: 'payment-link',
      description: 'صفحه پرداختی که در درگاه ساخته شده، مستقیم از اینجا باز می‌شود.',
      amount: 500000,
      currency: 'toman',
      customAmount: false,
      suggestedAmounts: [],
      minAmount: 0,
      maxAmount: 0,
      mode: 'link',
      region: 'ir',
      linkProvider: 'zarinpal',
      href: 'https://zarinpal.com/pg/StartPay/your-payment-link',
      recurring: false,
      cups: 4,
      active: true,
      featured: false,
      order: 5,
    },
    {
      title: 'کریپتو (USDT · TRC-20)',
      slug: 'crypto-usdt',
      description: 'از کیف پول خودت ارسال کن؛ پیش از تأیید، شبکه را بررسی کن.',
      amount: 10,
      currency: 'usd',
      customAmount: true,
      suggestedAmounts: [5, 10, 25],
      minAmount: 1,
      maxAmount: 1000,
      mode: 'crypto',
      region: 'global',
      crypto: { network: 'tron', address: 'TExampleWalletAddressReplaceMe1234' },
      recurring: false,
      cups: 3,
      active: true,
      featured: false,
      order: 6,
    },
    {
      title: 'پرداخت با کارت',
      slug: 'pay-by-card',
      description: 'پرداخت کارتی در صفحه درگاه و بازگشت به همین‌جا پس از پایان.',
      amount: 10,
      currency: 'usd',
      customAmount: false,
      suggestedAmounts: [],
      minAmount: 0,
      maxAmount: 0,
      mode: 'gateway',
      region: 'global',
      gateway: 'stripe',
      recurring: false,
      cups: 2,
      active: true,
      featured: true,
      order: 7,
    },
  ],
};

/**
 * Seed one option per rail so a fresh database shows the whole support page in
 * action. A persona never changes these; they are the site's payment plumbing.
 * Returns the inserted count.
 */
export const seedDonationData = async (_persona: Persona) => {
  const docs = withBothLangs(OPTIONS);
  if (!docs.length) return 0;

  const inserted = await donationModel.insertMany(docs);
  return inserted.length;
};
